apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- ingress.yaml

images:
- name: ghcr.io/chivta/kava.li/frontend
  newName: ghcr.io/chivta/kava.li/frontend
  newTag: 612b6ad565a965be562e1c28cadd3ff7658d3636
