apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- ingress.yaml

images:
- name: ghcr.io/chivta/kava.li/frontend
  newName: ghcr.io/chivta/kava.li/frontend
  newTag: f9d242cc59a124c7e2cd8cea51056c1ae2526cd3
