apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- ingress.yaml

images:
- name: ghcr.io/chivta/kava.li/frontend
  newName: ghcr.io/chivta/kava.li/frontend
  newTag: 6fe5f95972bf07babee5fb46b8bdd591793dbe93
